/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

import clases.Conexion;
import java.sql.*;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author leosa
 */
public class Capturista extends javax.swing.JFrame {

    String user;
    int sesion;
    
    public Capturista() {
        initComponents();
        user = Login.user;
        sesion = Administrador.sesionAdmi;
        
        setTitle("Capturista - Sesión de "+user);
        this.setTitle("Capturista");
        setLocationRelativeTo(null);
        setSize(550,300);
        setResizable(false);
        
        if (sesion == 1) {
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        }else{
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }
        
        ImageIcon fondoUrl = new ImageIcon("src/imagenes/wallpaperPrincipal.jpg");
        Icon fondo = new ImageIcon(fondoUrl.getImage().getScaledInstance(jLabelBack.getWidth(), jLabelBack.getHeight(), Image.SCALE_DEFAULT));
        jLabelBack.setIcon(fondo);
        repaint();
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select nombre_usuario from usuarios where username ='"+user+"'");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                titulo.setText("Bienvenido "+rs.getString("nombre_usuario"));
            }
        } catch (SQLException e) {
            System.err.println("Error de conexion con la base de datos "+e);
        }
    }
    
    @Override
    public Image getIconImage(){
        Image resValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
        return resValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        registerButton1 = new javax.swing.JButton();
        registerButton2 = new javax.swing.JButton();
        regi = new javax.swing.JLabel();
        regi1 = new javax.swing.JLabel();
        regi2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Registro de Usuarios");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        registerButton.setBackground(new java.awt.Color(204, 204, 204));
        registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 100, 90));

        registerButton1.setBackground(new java.awt.Color(204, 204, 204));
        registerButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informationuser.png"))); // NOI18N
        registerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(registerButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 100, 90));

        registerButton2.setBackground(new java.awt.Color(204, 204, 204));
        registerButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/impresora.png"))); // NOI18N
        registerButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(registerButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 100, 90));

        regi.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        regi.setForeground(new java.awt.Color(255, 255, 255));
        regi.setText("Imprimir Clientes");
        getContentPane().add(regi, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        regi1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        regi1.setForeground(new java.awt.Color(255, 255, 255));
        regi1.setText("Gestionar Clientes");
        getContentPane().add(regi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        regi2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        regi2.setForeground(new java.awt.Color(255, 255, 255));
        regi2.setText("Registrar Cliente");
        getContentPane().add(regi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sistema creado por Andre S. © ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));
        getContentPane().add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        new RegistroClientes().setVisible(true);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void registerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButton1ActionPerformed
        new GestionarClientes().setVisible(true);
    }//GEN-LAST:event_registerButton1ActionPerformed

    private void registerButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButton2ActionPerformed
        
        Document documento = new Document();
        
        try {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta+"/OneDrive/Escritorio/ReporteClientes.pdf"));
            
            com.itextpdf.text.Image header = com.itextpdf.text.Image.getInstance("src/imagenes/banerMio.png");
            header.scaleToFit(600,350);
            header.setAlignment(Chunk.ALIGN_CENTER);
            
            Paragraph parrafo = new Paragraph();
            parrafo.setFont(FontFactory.getFont("Tohoma",16,Font.BOLDITALIC,BaseColor.DARK_GRAY));
            parrafo.add("\n\n Información de los clientes\n\n");
            
            documento.open();
            
            documento.add(header);
            documento.add(parrafo);
            
            PdfPTable tablaClientes = new PdfPTable(5);
            
            tablaClientes.addCell("ID");
            tablaClientes.addCell("Nombre");
            tablaClientes.addCell("Email");
            tablaClientes.addCell("Telefono");
            tablaClientes.addCell("Dirección");
            
            try {
                Connection cn= Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement("select * from clientes");
                ResultSet rs = pst.executeQuery();
                
                while(rs.next()){
                    tablaClientes.addCell(rs.getString(1));
                    tablaClientes.addCell(rs.getString(2));
                    tablaClientes.addCell(rs.getString(3));
                    tablaClientes.addCell(rs.getString(4));
                    tablaClientes.addCell(rs.getString(5));
                    
                }
                documento.add(tablaClientes);
                
            } catch (DocumentException | SQLException e) {
                System.err.println("Eror con la conexion a base de datos: "+e);
            }
            documento.close();
            JOptionPane.showMessageDialog(null, "Reporte de clientes creado");
            
        } catch (DocumentException | HeadlessException | FileNotFoundException e) {
            System.err.println("Error en el documento pdf: " +e);
        }catch(IOException e){
            System.err.println("Error en el banner: "+e);
        }
    }//GEN-LAST:event_registerButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                          }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel regi;
    private javax.swing.JLabel regi1;
    private javax.swing.JLabel regi2;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton registerButton1;
    private javax.swing.JButton registerButton2;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
