/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

import java.sql.*;
import clases.Conexion;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import static ventanas.GestionarInventario.id_invetario;

public class GestionarInventarioUsado extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    public GestionarInventarioUsado() {
        initComponents();
        setResizable(false);
        this.setTitle("Gestion de inventario usado");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon fondo = new ImageIcon("src/imagenes/wallpaperPrincipal.jpg");
        Icon iconoFond = new ImageIcon(fondo.getImage().getScaledInstance(jLabelBack.getWidth(), jLabelBack.getHeight(), Image.SCALE_DEFAULT));
        jLabelBack.setIcon(iconoFond);
        repaint();
        
        model.setColumnCount(0);
        model.setRowCount(0);

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select * from inventario_usado");
            ResultSet rs = pst.executeQuery();

            tablaEquipos = new JTable(model);

            jScrollPane1.setViewportView(tablaEquipos);

            model.addColumn("ID");
            model.addColumn("ID inventario");
            model.addColumn("N serie");
            model.addColumn("Cantidad");
            model.addColumn("Inventario");
            model.addColumn("Fecha");

            
            while (rs.next()) {

                Object[] fila = new Object[6];
                for (int i = 0; i < 6; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            

        } catch (SQLException e) {
            System.err.println("Existe un error de conexion con la base de datos " + e);
        }
    }
    @Override
    public Image getIconImage() {
        Image ret = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
        return ret;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        buscarTxt = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEquipos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buscarBtn = new javax.swing.JButton();
        opcionTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabelBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Buscar por:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        buscarTxt.setBackground(new java.awt.Color(0, 102, 153));
        buscarTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        buscarTxt.setForeground(new java.awt.Color(255, 255, 255));
        buscarTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Numero de Serie", "Producto" }));
        buscarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTxtActionPerformed(evt);
            }
        });
        getContentPane().add(buscarTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 200, -1));

        jScrollPane1.setEnabled(false);

        tablaEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaEquipos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 730, 180));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inventario usado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sistema creado por Andre S. © ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        buscarBtn.setBackground(new java.awt.Color(0, 102, 153));
        buscarBtn.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        buscarBtn.setForeground(new java.awt.Color(255, 255, 255));
        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(buscarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 140, 30));

        opcionTxt.setBackground(new java.awt.Color(0, 102, 153));
        opcionTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        opcionTxt.setForeground(new java.awt.Color(255, 255, 255));
        opcionTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        opcionTxt.setBorder(null);
        getContentPane().add(opcionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 200, 25));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dato a buscar:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));
        getContentPane().add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarTxtActionPerformed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        model.setColumnCount(0);
        model.setRowCount(0);

        String buscar = buscarTxt.getSelectedItem().toString().trim();
        String opcion = opcionTxt.getText().trim();
        String query = null;

        if ((buscar.equals("Numero de Serie") || buscar.equals("Producto") || buscar.equals("Fecha")) && opcion.equals("")) {
            JOptionPane.showMessageDialog(null, "Complete los campos para generar la busqueda");
        } else {
            try {

                if (buscar.equals("Numero de Serie")) {
                    query = "select id,id_inventario,serie_equipo,cantidad,nombre_inventario,fecha_uso from inventario_usado where serie_equipo = '" + opcion + "'";
                } else if (buscar.equals("Producto")) {
                    query = "select id,id_inventario,serie_equipo,cantidad,nombre_inventario,fecha_uso from inventario_usado where nombre_inventario = '" + opcion + "'";
                }else if (buscar.equals("Todos")) {
                    query = "select id,id_inventario,serie_equipo,cantidad,nombre_inventario,fecha_uso from inventario_usado";
                }

                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(query); 
                ResultSet rs = pst.executeQuery();

                tablaEquipos = new JTable(model);

                jScrollPane1.setViewportView(tablaEquipos);

                model.addColumn("ID");
            model.addColumn("ID inventario");
            model.addColumn("N serie");
            model.addColumn("Cantidad");
            model.addColumn("Inventario");
            model.addColumn("Fecha");
                if (rs.next()) {
                    do {

                        Object[] fila = new Object[6];
                        for (int i = 0; i < 6; i++) {
                            fila[i] = rs.getObject(i + 1);
                        }                        
                        model.addRow(fila);
                    }while (rs.next());
                }else{
                        JOptionPane.showMessageDialog(null, "Opcion no encontrada. Por favor vuelva a intentar");
                }
                
            } catch (SQLException e) {
                System.err.println("Existe un error de conexion con la base de datos " + e);
            }
        }


    }//GEN-LAST:event_buscarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarInventarioUsado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarInventarioUsado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarInventarioUsado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarInventarioUsado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarInventarioUsado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarBtn;
    private javax.swing.JComboBox<String> buscarTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField opcionTxt;
    private javax.swing.JTable tablaEquipos;
    // End of variables declaration//GEN-END:variables
}
