/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

import java.sql.*;
import clases.Conexion;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leosa
 */
public class GestionarInventario extends javax.swing.JFrame {

    public static int id_invetario;

    DefaultTableModel model = new DefaultTableModel();

    public GestionarInventario() {
        initComponents();
        this.setTitle("Inventario - Sesion " + Login.user);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setTitle("Inventario - Sesión de " + Login.user);

        ImageIcon fond = new ImageIcon("src/imagenes/wallpaperPrincipal.jpg");
        Icon fondo = new ImageIcon(fond.getImage().getScaledInstance(jLabelBack.getWidth(), jLabelBack.getHeight(), Image.SCALE_DEFAULT));
        jLabelBack.setIcon(fondo);
        repaint();

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select id,nombre,referencia,cantidad,marca from inventario");
            ResultSet rs = pst.executeQuery();

            tablaEquipos = new JTable(model);

            jScrollPane1.setViewportView(tablaEquipos);

            model.addColumn(" ");
            model.addColumn("Nombre");
            model.addColumn("Referecia");
            model.addColumn("Cantidad");
            model.addColumn("Marca");

            while (rs.next()) {

                Object[] fila = new Object[5];
                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            tablaEquipos.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    int fila_point = tablaEquipos.rowAtPoint(e.getPoint());
                    int colum_point = 0;

                    if (fila_point > -1) {
                        id_invetario = (int) model.getValueAt(fila_point, colum_point);
                        new infoInventario().setVisible(true);
                    }
                }
            });

        } catch (SQLException e) {
            System.err.println("Existe un error de conexion con la base de datos " + e);
        }

    }

    @Override
    public Image getIconImage() {
        Image ret = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
        return ret;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        buscarTxt = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEquipos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buscarBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabelBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        opcionTxt.setBackground(new java.awt.Color(0, 102, 153));
        opcionTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        opcionTxt.setForeground(new java.awt.Color(255, 255, 255));
        opcionTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        opcionTxt.setBorder(null);
        getContentPane().add(opcionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 200, 25));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dato a buscar:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        buscarTxt.setBackground(new java.awt.Color(0, 102, 153));
        buscarTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        buscarTxt.setForeground(new java.awt.Color(255, 255, 255));
        buscarTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "nombre", "referencia", "marca" }));
        buscarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTxtActionPerformed(evt);
            }
        });
        getContentPane().add(buscarTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 200, -1));

        jScrollPane1.setEnabled(false);

        tablaEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaEquipos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 670, 180));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inventario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sistema creado por Andre S. © ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        buscarBtn.setBackground(new java.awt.Color(0, 102, 153));
        buscarBtn.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        buscarBtn.setForeground(new java.awt.Color(255, 255, 255));
        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(buscarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 140, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Categoria:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));
        getContentPane().add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarTxtActionPerformed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed

        model.setColumnCount(0);
        model.setRowCount(0);

        String buscar = buscarTxt.getSelectedItem().toString().trim();
        String opcion = opcionTxt.getText().trim();
        String query = null;

        if ((buscar.equals("nombre") || buscar.equals("referencia") || buscar.equals("marca")) && opcion.equals("")) {
            JOptionPane.showMessageDialog(null, "Complete los campos para generar la busqueda");
        } else {
            try {

                if (buscar.equals("nombre")) {
                    query = "select id,nombre,referencia,cantidad,marca from inventario where nombre = '" + opcion + "'";
                } else if (buscar.equals("referencia")) {
                    query = "select id,nombre,referencia,cantidad,marca from inventario where referencia = '" + opcion + "'";
                } else if (buscar.equals("marca")) {
                    query = "select id,nombre,referencia,cantidad,marca from inventario where marca = '" + opcion + "'";
                } else if (buscar.equals("Todos")) {
                    query = "select id,nombre,referencia,cantidad,marca from inventario";
                }

                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(query);
                ResultSet rs = pst.executeQuery();

                tablaEquipos = new JTable(model);

                jScrollPane1.setViewportView(tablaEquipos);

                model.addColumn(" ");
                model.addColumn("Nombre");
                model.addColumn("Referecia");
                model.addColumn("Cantidad");
                model.addColumn("Marca");

                if (rs.next()) {
                    do {

                        Object[] fila = new Object[5];
                        for (int i = 0; i < 5; i++) {
                            fila[i] = rs.getObject(i + 1);
                        }                        
                        model.addRow(fila);
                    }while (rs.next());
                }else{
                        JOptionPane.showMessageDialog(null, "Opcion no encontrada. Por favor vuelva a intentar");
                }
                tablaEquipos.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        int fila_point = tablaEquipos.rowAtPoint(e.getPoint());
                        int colum_point = 0;

                        if (fila_point > -1) {
                            id_invetario = (int) model.getValueAt(fila_point, colum_point);
                            new infoInventario().setVisible(true);
                        }
                    }
                });

            } catch (SQLException e) {
                System.err.println("Existe un error de conexion con la base de datos " + e);
            }
        }


    }//GEN-LAST:event_buscarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarBtn;
    private javax.swing.JComboBox<String> buscarTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField opcionTxt;
    private javax.swing.JTable tablaEquipos;
    // End of variables declaration//GEN-END:variables
}
