/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;

import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import java.sql.*;
import java.sql.Date;
import static ventanas.Login.user;

public class infoInventario extends javax.swing.JFrame {

    int id_inven;    
    String user;
    String tipo_nivel;
    
    public infoInventario() {
        initComponents();
        
        user= Login.user;
        id_inven = GestionarInventario.id_invetario;
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
        

        ImageIcon fondoUrl = new ImageIcon("src/imagenes/wallpaperPrincipal.jpg");
        Icon fondo = new ImageIcon(fondoUrl.getImage().getScaledInstance(jLabelBack.getWidth(), jLabelBack.getHeight(), Image.SCALE_DEFAULT));
        jLabelBack.setIcon(fondo);
        repaint();
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select tipo_nivel from usuarios where username = '" + user + "'");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {

                tipo_nivel = rs.getString("tipo_nivel");

                if (tipo_nivel.equalsIgnoreCase("Administrador")) {
                    NombreTxt.setEditable(true);
                    refeTxt.setEditable(true);
                    cantidadTxt.setEditable(true);
                    marcaTxt.setEditable(true);                    
                } else {
                    NombreTxt.setEditable(false);
                    refeTxt.setEditable(false);
                    cantidadTxt.setEditable(false);
                    marcaTxt.setEditable(false);
                    eliminarBtn.setVisible(false);
                    actualizarBtn.setVisible(false);
                }

            }
        } catch (SQLException e) {
            System.err.println("Error en el boton Acceder: " + e);
            JOptionPane.showMessageDialog(null, "Eror al iniciar sesion!!, contacte al administrador.");
        }

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select * from inventario where id =  '" + id_inven + "'");

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                this.setTitle("Producto "+rs.getString("nombre"));
                NombreTxt.setText(rs.getString("nombre"));
                refeTxt.setText(rs.getString("referencia"));
                cantidadTxt.setText(rs.getString("cantidad"));
                fechaRegistroTxt.setText(rs.getString("fecha_registro"));
                ultimaTxt.setText(rs.getString("ultima_actualizacion"));
                marcaTxt.setText(rs.getString("marca"));
                registradoTxt.setText(rs.getString("registrado_por"));
                actualizadoTxt.setText(rs.getString("actualizado_por"));

                cn.close();
            }
        } catch (SQLException e) {
            System.err.println("Error con la base de datos " + e);
        }
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
        return retValue;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        modificadoTxt1 = new javax.swing.JTextField();
        actualizarBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NombreTxt = new javax.swing.JTextField();
        refeTxt = new javax.swing.JTextField();
        cantidadTxt = new javax.swing.JTextField();
        marcaTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ultimaTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        actualizarBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        actualizadoTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fechaRegistroTxt = new javax.swing.JTextField();
        eliminarBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        registradoTxt = new javax.swing.JTextField();
        jLabelBack = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registrado por:");

        modificadoTxt1.setBackground(new java.awt.Color(0, 102, 153));
        modificadoTxt1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        modificadoTxt1.setForeground(new java.awt.Color(255, 255, 255));
        modificadoTxt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        modificadoTxt1.setBorder(null);
        modificadoTxt1.setEnabled(false);
        modificadoTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificadoTxt1ActionPerformed(evt);
            }
        });

        actualizarBtn1.setBackground(new java.awt.Color(0, 102, 153));
        actualizarBtn1.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        actualizarBtn1.setForeground(new java.awt.Color(255, 255, 255));
        actualizarBtn1.setText("Actualizar  producto");
        actualizarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarBtn1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("informacion del producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        NombreTxt.setBackground(new java.awt.Color(0, 102, 153));
        NombreTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NombreTxt.setForeground(new java.awt.Color(255, 255, 255));
        NombreTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NombreTxt.setBorder(null);
        NombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTxtActionPerformed(evt);
            }
        });
        getContentPane().add(NombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 200, 25));

        refeTxt.setBackground(new java.awt.Color(0, 102, 153));
        refeTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        refeTxt.setForeground(new java.awt.Color(255, 255, 255));
        refeTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        refeTxt.setBorder(null);
        getContentPane().add(refeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 200, 25));

        cantidadTxt.setBackground(new java.awt.Color(0, 102, 153));
        cantidadTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cantidadTxt.setForeground(new java.awt.Color(255, 255, 255));
        cantidadTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidadTxt.setBorder(null);
        getContentPane().add(cantidadTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 200, 25));

        marcaTxt.setBackground(new java.awt.Color(0, 102, 153));
        marcaTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        marcaTxt.setForeground(new java.awt.Color(255, 255, 255));
        marcaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        marcaTxt.setBorder(null);
        marcaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaTxtActionPerformed(evt);
            }
        });
        getContentPane().add(marcaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 200, 25));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Referencia");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ultima actualización:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Marca:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        ultimaTxt.setBackground(new java.awt.Color(0, 102, 153));
        ultimaTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ultimaTxt.setForeground(new java.awt.Color(255, 255, 255));
        ultimaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ultimaTxt.setBorder(null);
        ultimaTxt.setEnabled(false);
        ultimaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimaTxtActionPerformed(evt);
            }
        });
        getContentPane().add(ultimaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 200, 25));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        actualizarBtn.setBackground(new java.awt.Color(0, 102, 153));
        actualizarBtn.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        actualizarBtn.setForeground(new java.awt.Color(255, 255, 255));
        actualizarBtn.setText("Actualizar  producto");
        actualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(actualizarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 200, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Actualizado por:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        actualizadoTxt.setBackground(new java.awt.Color(0, 102, 153));
        actualizadoTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        actualizadoTxt.setForeground(new java.awt.Color(255, 255, 255));
        actualizadoTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        actualizadoTxt.setBorder(null);
        actualizadoTxt.setEnabled(false);
        actualizadoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizadoTxtActionPerformed(evt);
            }
        });
        getContentPane().add(actualizadoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 200, 25));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha de registro:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        fechaRegistroTxt.setBackground(new java.awt.Color(0, 102, 153));
        fechaRegistroTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fechaRegistroTxt.setForeground(new java.awt.Color(255, 255, 255));
        fechaRegistroTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechaRegistroTxt.setBorder(null);
        fechaRegistroTxt.setEnabled(false);
        fechaRegistroTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaRegistroTxtActionPerformed(evt);
            }
        });
        getContentPane().add(fechaRegistroTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 200, 25));

        eliminarBtn.setBackground(new java.awt.Color(0, 102, 153));
        eliminarBtn.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        eliminarBtn.setForeground(new java.awt.Color(255, 255, 255));
        eliminarBtn.setText("Eliminar producto");
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 200, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Registrado por:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        registradoTxt.setBackground(new java.awt.Color(0, 102, 153));
        registradoTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        registradoTxt.setForeground(new java.awt.Color(255, 255, 255));
        registradoTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        registradoTxt.setBorder(null);
        registradoTxt.setEnabled(false);
        registradoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registradoTxtActionPerformed(evt);
            }
        });
        getContentPane().add(registradoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 200, 25));
        getContentPane().add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtActionPerformed

    private void marcaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaTxtActionPerformed

    private void ultimaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ultimaTxtActionPerformed

    private void actualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarBtnActionPerformed
        String nombre = NombreTxt.getText().trim();
        String referencia = refeTxt.getText().trim();
        String cantidad = cantidadTxt.getText().trim();
        String marca = marcaTxt.getText().trim();
        long mili = System.currentTimeMillis();
        Date fecha = new Date(mili);

        if (nombre.equals("") || referencia.equals("") || cantidad.equals("") || marca.equals("")) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        } else {
            try {
                Connection cn1 = Conexion.conectar();
                PreparedStatement pst1 = cn1.prepareStatement("update inventario set nombre=?,referencia=?,cantidad=?,marca=?,ultima_actualizacion=?,actualizado_por=? where id='" + id_inven + "'");

                pst1.setString(1, nombre);
                pst1.setString(2, referencia);
                pst1.setInt(3, Integer.parseInt(cantidad));
                pst1.setString(4, marca);
                pst1.setDate(5, fecha);
                pst1.setString(6, user);
                pst1.executeUpdate();
                cn1.close();

                JOptionPane.showMessageDialog(null, "Producto actualizado");

                this.dispose();

            } catch (SQLException e) {
                System.err.println("Existe un error de conexion con la base de datos " + e);
            }
        }
    }//GEN-LAST:event_actualizarBtnActionPerformed

    private void modificadoTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificadoTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificadoTxt1ActionPerformed

    private void actualizadoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizadoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualizadoTxtActionPerformed

    private void fechaRegistroTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaRegistroTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaRegistroTxtActionPerformed

    private void actualizarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualizarBtn1ActionPerformed

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "Esta seguro que quiere eliminar este producto del inventario?");
        
        if(respuesta==0){
            try {
                Connection cn1 = Conexion.conectar();
                PreparedStatement pst1 = cn1.prepareStatement("delete from inventario where id='" + id_inven + "'");
                pst1.executeUpdate();

                
                cn1.close();
                JOptionPane.showMessageDialog(null, "Producto eliminado correctamente");
                this.dispose();

            } catch (SQLException e) {
                System.err.println("Existe un error de conexion con la base de datos " + e);
            }
        }
    }//GEN-LAST:event_eliminarBtnActionPerformed

    private void registradoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registradoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registradoTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(infoInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(infoInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(infoInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(infoInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new infoInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JTextField actualizadoTxt;
    private javax.swing.JButton actualizarBtn;
    private javax.swing.JButton actualizarBtn1;
    private javax.swing.JTextField cantidadTxt;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JTextField fechaRegistroTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JTextField marcaTxt;
    private javax.swing.JTextField modificadoTxt1;
    private javax.swing.JTextField refeTxt;
    private javax.swing.JTextField registradoTxt;
    private javax.swing.JTextField ultimaTxt;
    // End of variables declaration//GEN-END:variables
}
