/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import clases.Conexion;
import java.sql.*;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import static ventanas.Login.user;

/**
 *
 * @author leosa
 */
public class infoEquipo extends javax.swing.JFrame {

    String num_serie;
    String tipo_nivel;

    public infoEquipo() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Información del equipo - Cliente " + infoCliente.nombre_cliente);

        ImageIcon fond = new ImageIcon("src/imagenes/wallpaperPrincipal.jpg");
        Icon fondo = new ImageIcon(fond.getImage().getScaledInstance(jLabelBack1.getWidth(), jLabelBack1.getHeight(), Image.SCALE_DEFAULT));
        jLabelBack1.setIcon(fondo);
        repaint();

        nombreTxt.setText(infoCliente.nombre_cliente);

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select tipo_nivel from usuarios where username = '" + user + "'");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {

                tipo_nivel = rs.getString("tipo_nivel");

                if (tipo_nivel.equalsIgnoreCase("Administrador") || tipo_nivel.equalsIgnoreCase("Tecnico")) {
                    statusTxt.setEditable(true);
                    comenTxt.setEditable(true);
                    num_serie = GestionarEquipos.num_serie;
                } else {
                    statusTxt.setEditable(false);
                    comenTxt.setEditable(false);
                    num_serie = infoCliente.num_serie;
                }

            }
        } catch (SQLException e) {
            System.err.println("Error en el boton Acceder: " + e);
            JOptionPane.showMessageDialog(null, "Eror al iniciar sesion!!, contacte al administrador.");
        }

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select * from equipos where  num_serie='" + num_serie + "'");

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                tipoEqui.setSelectedItem(rs.getString("tipo_equipo"));
                marcaTxt.setSelectedItem(rs.getString("marca"));
                modeloTxt.setText(rs.getString("modelo"));
                serieTxt.setText(rs.getString("num_serie"));
                observacionesTxt.setText(rs.getString("observaciones"));
                comenTxt.setText(rs.getString("comentarios_tecnicos"));
                statusTxt.setSelectedItem(rs.getString("estatus"));
                fechaTxt.setText(rs.getString("fecha_ingreso"));
                tecnicoTxt.setText(rs.getString("revision_tecnica"));
            }
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error de conexion con la tabla equipo " + e);
        }
    }

    @Override
    public Image getIconImage() {
        Image ret = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
        return ret;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        serieTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tipoEqui = new javax.swing.JComboBox<>();
        marcaTxt = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        comenTxt = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        actualizarEquipo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        observacionesTxt = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        modeloTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fechaTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tecnicoTxt = new javax.swing.JTextField();
        statusTxt = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        piezaBtn = new javax.swing.JButton();
        jLabelBack1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreTxt.setBackground(new java.awt.Color(0, 102, 153));
        nombreTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nombreTxt.setForeground(new java.awt.Color(255, 255, 255));
        nombreTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreTxt.setBorder(null);
        nombreTxt.setEnabled(false);
        getContentPane().add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 200, 25));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Marca:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        serieTxt.setBackground(new java.awt.Color(0, 102, 153));
        serieTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        serieTxt.setForeground(new java.awt.Color(255, 255, 255));
        serieTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        serieTxt.setBorder(null);
        serieTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serieTxtActionPerformed(evt);
            }
        });
        getContentPane().add(serieTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 200, 25));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Comentarios tecnicos:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha de ingreso:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tecnico encargado:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Informacion del equipo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        tipoEqui.setBackground(new java.awt.Color(0, 102, 153));
        tipoEqui.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tipoEqui.setForeground(new java.awt.Color(255, 255, 255));
        tipoEqui.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Laptop", "Impresora", "Telefono", "Desktop", "Tablet" }));
        tipoEqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoEquiActionPerformed(evt);
            }
        });
        getContentPane().add(tipoEqui, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 200, -1));

        marcaTxt.setBackground(new java.awt.Color(0, 102, 153));
        marcaTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        marcaTxt.setForeground(new java.awt.Color(255, 255, 255));
        marcaTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Asus", "Apple", "Samsung", "Lenovo", "Acer", "Hp", "Xiaomi", "Huawei", "Motorola", "Oppo", "Sony", "Cannon", "Epson" }));
        getContentPane().add(marcaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 200, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Numero de serie:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        comenTxt.setColumns(20);
        comenTxt.setRows(5);
        jScrollPane1.setViewportView(comenTxt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 330, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo equipo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        actualizarEquipo.setBackground(new java.awt.Color(0, 102, 153));
        actualizarEquipo.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        actualizarEquipo.setForeground(new java.awt.Color(255, 255, 255));
        actualizarEquipo.setText("Actualizar Equipo");
        actualizarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(actualizarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 200, 30));

        observacionesTxt.setColumns(20);
        observacionesTxt.setRows(5);
        jScrollPane2.setViewportView(observacionesTxt);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 330, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Observaciones:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        modeloTxt.setBackground(new java.awt.Color(0, 102, 153));
        modeloTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        modeloTxt.setForeground(new java.awt.Color(255, 255, 255));
        modeloTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        modeloTxt.setBorder(null);
        getContentPane().add(modeloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 200, 25));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Modelo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        fechaTxt.setBackground(new java.awt.Color(0, 102, 153));
        fechaTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fechaTxt.setForeground(new java.awt.Color(255, 255, 255));
        fechaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechaTxt.setBorder(null);
        fechaTxt.setEnabled(false);
        getContentPane().add(fechaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 200, 25));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombre cliente:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        tecnicoTxt.setBackground(new java.awt.Color(0, 102, 153));
        tecnicoTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tecnicoTxt.setForeground(new java.awt.Color(255, 255, 255));
        tecnicoTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tecnicoTxt.setText("Ingresado");
        tecnicoTxt.setBorder(null);
        tecnicoTxt.setEnabled(false);
        tecnicoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecnicoTxtActionPerformed(evt);
            }
        });
        getContentPane().add(tecnicoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 200, 25));

        statusTxt.setBackground(new java.awt.Color(0, 102, 153));
        statusTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        statusTxt.setForeground(new java.awt.Color(255, 255, 255));
        statusTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingresado", "En revision", "Reparado", "No  reparado", "Entrega" }));
        statusTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTxtActionPerformed(evt);
            }
        });
        getContentPane().add(statusTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 200, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Estado:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        piezaBtn.setBackground(new java.awt.Color(0, 102, 153));
        piezaBtn.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        piezaBtn.setForeground(new java.awt.Color(255, 255, 255));
        piezaBtn.setText("Piezas");
        piezaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piezaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(piezaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 200, 30));
        getContentPane().add(jLabelBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serieTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serieTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serieTxtActionPerformed

    private void tipoEquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoEquiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoEquiActionPerformed

    private void actualizarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarEquipoActionPerformed
        String marca = marcaTxt.getSelectedItem().toString().trim();
        String tipo = tipoEqui.getSelectedItem().toString().trim();
        String modelo = modeloTxt.getText().trim();
        String serie = serieTxt.getText().trim();
        String obser = observacionesTxt.getText().trim();
        String status = statusTxt.getSelectedItem().toString().trim();
        String comen = comenTxt.getText().trim();

        if (modelo.equals("") || serie.equals("") || obser.equals("")) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        } else if (marca.equals("Seleccionar") || tipo.equals("Seleccionar")) {
            JOptionPane.showMessageDialog(null, "Seleccione una opción");
        } else {
            if (status.equals("Entrega") || status.equals("Reparado")) {
                if (JOptionPane.showConfirmDialog(null, "Si ya agrego las piezas usadas en este equipo, oprima 'yes' de lo contrario agregarlas") == 0) {
                    try {
                        Connection cn = Conexion.conectar();
                        if (tipo_nivel.equalsIgnoreCase("Tecnico")) {
                            PreparedStatement pst = cn.prepareStatement("update equipos set tipo_equipo=?, marca=?,modelo=?,num_serie=?,observaciones=?,estatus=?,comentarios_tecnicos=?,revision_tecnica=? where num_serie='" + num_serie + "'");
                            pst.setString(1, tipo);
                            pst.setString(2, marca);
                            pst.setString(3, modelo);
                            pst.setString(4, serie);
                            pst.setString(5, obser);
                            pst.setString(6, status);
                            pst.setString(7, comen);
                            pst.setString(8, Login.user);

                            pst.executeUpdate();
                            cn.close();
                        } else {
                            PreparedStatement pst = cn.prepareStatement("update equipos set tipo_equipo=?, marca=?,modelo=?,num_serie=?,observaciones=? where num_serie='" + num_serie + "'");
                            pst.setString(1, tipo);
                            pst.setString(2, marca);
                            pst.setString(3, modelo);
                            pst.setString(4, serie);
                            pst.setString(5, obser);

                            pst.executeUpdate();
                            cn.close();
                        }
                        JOptionPane.showMessageDialog(null, "Equipo actualizado correctamente");
                        this.dispose();

                    } catch (SQLException e) {
                        System.err.println("Existe un error de conexion con la base de datos " + e);
                    }
                }
            }

        }
    }//GEN-LAST:event_actualizarEquipoActionPerformed

    private void tecnicoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecnicoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tecnicoTxtActionPerformed

    private void statusTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTxtActionPerformed

    private void piezaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piezaBtnActionPerformed
        new Piezas().setVisible(true);
    }//GEN-LAST:event_piezaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(infoEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(infoEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(infoEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(infoEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new infoEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarEquipo;
    private javax.swing.JTextArea comenTxt;
    private javax.swing.JTextField fechaTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBack1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> marcaTxt;
    private javax.swing.JTextField modeloTxt;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextArea observacionesTxt;
    private javax.swing.JButton piezaBtn;
    private javax.swing.JTextField serieTxt;
    private javax.swing.JComboBox<String> statusTxt;
    private javax.swing.JTextField tecnicoTxt;
    private javax.swing.JComboBox<String> tipoEqui;
    // End of variables declaration//GEN-END:variables
}
