/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import clases.Conexion;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class infoUsuario extends javax.swing.JFrame {

    String user = "" ;
    public static String user_update= GestionarUsuarios.user_update;
    int id;

    public infoUsuario() {
        initComponents();
        user = Login.user;

        setTitle("Información del usuario " + user_update + " -Sesión de " + user);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
        setSize(620,430);

        ImageIcon fondoUrl = new ImageIcon("src/imagenes/wallpaperPrincipal.jpg");
        Icon fondo = new ImageIcon(fondoUrl.getImage().getScaledInstance(jLabelBack.getWidth(), jLabelBack.getHeight(), Image.SCALE_DEFAULT));
        jLabelBack.setIcon(fondo);
        repaint();

        titulo.setText("Informacion del usuario " + user_update);

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select * from usuarios where username =  '" + user_update + "'");

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                id = rs.getInt("id"); 
                NombreTxt.setText(rs.getString("nombre_usuario"));
                emailTxt.setText(rs.getString("email"));
                telTxt.setText(rs.getString("telefono"));
                usernameTxt.setText(rs.getString("username"));
                permiso.setSelectedItem(rs.getString("tipo_nivel"));
                statusTxt.setSelectedItem(rs.getString("estatus"));
                registradoPor.setText(rs.getString("registrado_por"));

                cn.close();
            }
        } catch (SQLException e) {
            System.err.println("Error con la base de datos " + e);
        }

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        NombreTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        telTxt = new javax.swing.JTextField();
        usernameTxt = new javax.swing.JTextField();
        statusTxt = new javax.swing.JComboBox<>();
        permiso = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        restaurarBtn = new javax.swing.JButton();
        actualizarBtn = new javax.swing.JButton();
        registradoPor = new javax.swing.JTextField();
        jLabelBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setPreferredSize(new java.awt.Dimension(620, 430));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Información del Usuario");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        NombreTxt.setBackground(new java.awt.Color(0, 102, 153));
        NombreTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NombreTxt.setForeground(new java.awt.Color(255, 255, 255));
        NombreTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NombreTxt.setBorder(null);
        NombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTxtActionPerformed(evt);
            }
        });
        getContentPane().add(NombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 200, 25));

        emailTxt.setBackground(new java.awt.Color(0, 102, 153));
        emailTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(255, 255, 255));
        emailTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailTxt.setBorder(null);
        getContentPane().add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 200, 25));

        telTxt.setBackground(new java.awt.Color(0, 102, 153));
        telTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        telTxt.setForeground(new java.awt.Color(255, 255, 255));
        telTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telTxt.setBorder(null);
        getContentPane().add(telTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 200, 25));

        usernameTxt.setBackground(new java.awt.Color(0, 102, 153));
        usernameTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        usernameTxt.setForeground(new java.awt.Color(255, 255, 255));
        usernameTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameTxt.setBorder(null);
        getContentPane().add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 200, 25));

        statusTxt.setBackground(new java.awt.Color(0, 102, 153));
        statusTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        statusTxt.setForeground(new java.awt.Color(255, 255, 255));
        statusTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        getContentPane().add(statusTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 200, -1));

        permiso.setBackground(new java.awt.Color(0, 102, 153));
        permiso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        permiso.setForeground(new java.awt.Color(255, 255, 255));
        permiso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Capturista", "Tecnico" }));
        getContentPane().add(permiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 270, 200, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefono:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Permiso de:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre de Usuario:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Registrado por:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Status:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        restaurarBtn.setBackground(new java.awt.Color(0, 102, 153));
        restaurarBtn.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        restaurarBtn.setForeground(new java.awt.Color(255, 255, 255));
        restaurarBtn.setText("Restaurar Password");
        restaurarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(restaurarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 200, 30));

        actualizarBtn.setBackground(new java.awt.Color(0, 102, 153));
        actualizarBtn.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        actualizarBtn.setForeground(new java.awt.Color(255, 255, 255));
        actualizarBtn.setText("Actualizar Usuario");
        actualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(actualizarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 200, 30));

        registradoPor.setBackground(new java.awt.Color(0, 102, 153));
        registradoPor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        registradoPor.setForeground(new java.awt.Color(255, 255, 255));
        registradoPor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        registradoPor.setBorder(null);
        registradoPor.setEnabled(false);
        registradoPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registradoPorActionPerformed(evt);
            }
        });
        getContentPane().add(registradoPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 200, 25));
        getContentPane().add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtActionPerformed

    private void restaurarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurarBtnActionPerformed
        new RestaurarPassword().setVisible(true);
    }//GEN-LAST:event_restaurarBtnActionPerformed

    private void actualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarBtnActionPerformed
        String nombre = NombreTxt.getText();
        String email = emailTxt.getText();
        String tel = telTxt.getText();
        String user = usernameTxt.getText();

        if (nombre.equals("") || email.equals("") || tel.equals("") || user.equals("")) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        } else {
            try {
                Connection cn1 = Conexion.conectar();
                PreparedStatement pst1 = cn1.prepareStatement("select * from usuarios where username = '"+user+"' and not id = '"+id+"'");
                
                ResultSet rs = pst1.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "El usuario ya existe, por favor ingrese otro nuevamente");
                    cn1.close();
            } else {
                try {
                    Connection cn = Conexion.conectar();
                    PreparedStatement pst = cn.prepareStatement("update usuarios set nombre_usuario = ?, email = ?, telefono = ?, username = ?,tipo_nivel = ?,estatus = ? where id = '" + id + "'");

                    pst.setString(1, nombre);
                    pst.setString(2, email);
                    pst.setString(3, tel);
                    pst.setString(4, user);
                    pst.setString(5, permiso.getSelectedItem().toString().trim());
                    pst.setString(6, statusTxt.getSelectedItem().toString().trim());

                    pst.executeUpdate();

                    NombreTxt.setText("");
                    emailTxt.setText("");
                    telTxt.setText("");
                    usernameTxt.setText("");
                    permiso.setSelectedIndex(1);
                    statusTxt.setSelectedIndex(1);

                    JOptionPane.showMessageDialog(null, "El registro fue modificado correctamente");
                } catch (SQLException e) {
                    System.err.println("Existe un error de conexion con la base de datos " + e);
                }
            }
            } catch (SQLException e) {
                System.err.println("Existe un error de conexion con la base de datos " + e);
            }
        }
    }//GEN-LAST:event_actualizarBtnActionPerformed

    private void registradoPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registradoPorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registradoPorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(infoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(infoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(infoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(infoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new infoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JButton actualizarBtn;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JComboBox<String> permiso;
    private javax.swing.JTextField registradoPor;
    private javax.swing.JButton restaurarBtn;
    private javax.swing.JComboBox<String> statusTxt;
    private javax.swing.JTextField telTxt;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
