/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

import java.sql.*;
import clases.Conexion;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

public class Piezas extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    String num_serie;
    public static int id_usado;

    public Piezas() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        num_serie = GestionarEquipos.num_serie;

        ImageIcon fondo = new ImageIcon("src/imagenes/wallpaperPrincipal.jpg");
        Icon iconoFond = new ImageIcon(fondo.getImage().getScaledInstance(jLabelBack.getWidth(), jLabelBack.getHeight(), Image.SCALE_DEFAULT));
        jLabelBack.setIcon(iconoFond);
        repaint();

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select id,cantidad,serie_equipo,nombre_inventario from inventario_usado where serie_equipo = '"+num_serie+"'");
            ResultSet rs = pst.executeQuery();

            tablaPiezas = new JTable(model);
            jScrollPane1.setViewportView(tablaPiezas);

            model.addColumn("ID");
            model.addColumn("Cantidad");
            model.addColumn("Equipo");
            model.addColumn("Pieza");

            if (rs.next()) {
                do {
                    Object[] fila = new Object[4];
                    for (int i = 0; i < 4; i++) {
                        fila[i] = rs.getObject(i + 1);
                    }
                    model.addRow(fila);
                } while (rs.next());
            }else{
                jScrollPane1.setVisible(false);
            }
        } catch (SQLException e) {
            System.err.println("Error de conexion con la base de datos: "+e);
        }
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarBtn1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPiezas = new javax.swing.JTable();
        agregarPiezasBtn = new javax.swing.JButton();
        alerta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelBack = new javax.swing.JLabel();

        buscarBtn1.setBackground(new java.awt.Color(0, 102, 153));
        buscarBtn1.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        buscarBtn1.setForeground(new java.awt.Color(255, 255, 255));
        buscarBtn1.setText("Buscar");
        buscarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtn1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setEnabled(false);

        tablaPiezas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPiezas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 670, 130));

        agregarPiezasBtn.setBackground(new java.awt.Color(0, 102, 153));
        agregarPiezasBtn.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        agregarPiezasBtn.setForeground(new java.awt.Color(255, 255, 255));
        agregarPiezasBtn.setText("Agregar piezas");
        agregarPiezasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPiezasBtnActionPerformed(evt);
            }
        });
        getContentPane().add(agregarPiezasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 190, 30));

        alerta.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        alerta.setForeground(new java.awt.Color(255, 255, 255));
        alerta.setText("Este dispositivo no tiene piezas agregadas");
        getContentPane().add(alerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Piezas usadas por ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));
        getContentPane().add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarPiezasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPiezasBtnActionPerformed
        new RegistroPieza().setVisible(true);
        

    }//GEN-LAST:event_agregarPiezasBtnActionPerformed

    private void buscarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Piezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Piezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Piezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Piezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Piezas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarPiezasBtn;
    private javax.swing.JLabel alerta;
    private javax.swing.JButton buscarBtn1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPiezas;
    // End of variables declaration//GEN-END:variables
}
