/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import clases.Conexion;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class RegistroUsuarios extends javax.swing.JFrame {

    String userLog = Login.user;

    public RegistroUsuarios() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(630, 400);
        setResizable(false);

        ImageIcon urlImagen = new ImageIcon("src/imagenes/wallpaperPrincipal.jpg");
        Icon fondo = new ImageIcon(urlImagen.getImage().getScaledInstance(jLabelBack.getWidth(), jLabelBack.getHeight(), Image.SCALE_DEFAULT));
        jLabelBack.setIcon(fondo);
        repaint();
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NombreTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        telTxt = new javax.swing.JTextField();
        usernameTxt = new javax.swing.JTextField();
        statusTxt = new javax.swing.JComboBox<>();
        passwordTxt = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabelBack = new javax.swing.JLabel();

        jTextField2.setBackground(new java.awt.Color(0, 102, 153));
        jTextField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(null);

        jTextField3.setBackground(new java.awt.Color(0, 102, 153));
        jTextField3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setBorder(null);

        jTextField4.setBackground(new java.awt.Color(0, 102, 153));
        jTextField4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de Usuarios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        NombreTxt.setBackground(new java.awt.Color(0, 102, 153));
        NombreTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NombreTxt.setForeground(new java.awt.Color(255, 255, 255));
        NombreTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NombreTxt.setBorder(null);
        NombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTxtActionPerformed(evt);
            }
        });
        getContentPane().add(NombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 200, 25));

        emailTxt.setBackground(new java.awt.Color(0, 102, 153));
        emailTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(255, 255, 255));
        emailTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailTxt.setBorder(null);
        getContentPane().add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 200, 25));

        telTxt.setBackground(new java.awt.Color(0, 102, 153));
        telTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        telTxt.setForeground(new java.awt.Color(255, 255, 255));
        telTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telTxt.setBorder(null);
        getContentPane().add(telTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 200, 25));

        usernameTxt.setBackground(new java.awt.Color(0, 102, 153));
        usernameTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        usernameTxt.setForeground(new java.awt.Color(255, 255, 255));
        usernameTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameTxt.setBorder(null);
        getContentPane().add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 200, 25));

        statusTxt.setBackground(new java.awt.Color(0, 102, 153));
        statusTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        statusTxt.setForeground(new java.awt.Color(255, 255, 255));
        statusTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Capturista", "Tecnico" }));
        getContentPane().add(statusTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 270, 200, -1));

        passwordTxt.setBackground(new java.awt.Color(0, 102, 153));
        passwordTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        passwordTxt.setForeground(new java.awt.Color(255, 255, 255));
        passwordTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordTxt.setBorder(null);
        getContentPane().add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 200, 25));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefono:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Permiso de:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre de Usuario:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        registerButton.setBackground(new java.awt.Color(204, 204, 204));
        registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 221, 100, 90));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sistema creado por Andre S. © ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));
        getContentPane().add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String nombre = NombreTxt.getText().trim();
        String email = emailTxt.getText().trim();
        String tel = telTxt.getText().trim();
        String user = usernameTxt.getText().trim();
        String pass = passwordTxt.getText().trim();
        if (nombre.equals("") || email.equals("") || tel.equals("") || user.equals("") || pass.equals("")) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        } else {
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst1 = cn.prepareStatement("select * from usuarios where username = '" + usernameTxt.getText().trim() + "'");

                ResultSet rs = pst1.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Nombre de usuario ya registrado");
                    cn.close();
                } else {
                    try {
                        cn.close();
                        
                        Connection cn2 = Conexion.conectar();
                        PreparedStatement pst = cn2.prepareStatement("insert into usuarios values(?,?,?,?,?,?,?,?,?)");

                        pst.setString(1, "0");
                        pst.setString(2, NombreTxt.getText().trim());
                        pst.setString(3, emailTxt.getText().trim());
                        pst.setString(4, telTxt.getText().trim());
                        pst.setString(5, usernameTxt.getText().trim());
                        pst.setString(6, passwordTxt.getText().trim());
                        pst.setString(7, statusTxt.getSelectedItem().toString().trim());
                        pst.setString(8, "Activo");
                        pst.setNString(9, userLog.trim());

                        pst.executeUpdate();
                        cn2.close();

                        JOptionPane.showMessageDialog(null, "Registro exitoso");

                        NombreTxt.setText("");
                        emailTxt.setText("");
                        telTxt.setText("");
                        usernameTxt.setText("");
                        passwordTxt.setText("");
                        //esta linea de condigo pone la primera opcion que se encuentra dentro del comboBox
                        statusTxt.setSelectedIndex(0);
                        
                        this.dispose();
                    } catch (SQLException e) {
                        System.err.println("Existe un problema de conexion con la base de datos: " + e);
                    }
                }
            } catch (SQLException e) {
                System.err.println("Problema de conexion con la base de datos "+ e);
            }

        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void NombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JButton registerButton;
    private javax.swing.JComboBox<String> statusTxt;
    private javax.swing.JTextField telTxt;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
