/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

import clases.Conexion;
import java.sql.*;

/**
 *
 * @author leosa
 */
public class RegistroPieza extends javax.swing.JFrame {

    int id_inve,cantidad_inventario,resultado;
    String num_serie;
    public RegistroPieza() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        num_serie=GestionarEquipos.num_serie;       
        ImageIcon fondo = new ImageIcon("src/imagenes/wallpaperPrincipal.jpg");
        Icon iconoFond = new ImageIcon(fondo.getImage().getScaledInstance(jLabelBack.getWidth(), jLabelBack.getHeight(), Image.SCALE_DEFAULT));
        jLabelBack.setIcon(iconoFond);
        repaint();
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
        return retValue;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NombreTxt = new javax.swing.JTextField();
        referTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cantidadTxt = new javax.swing.JTextField();
        agregarBtn = new javax.swing.JButton();
        jLabelBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de pieza para ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        NombreTxt.setBackground(new java.awt.Color(0, 102, 153));
        NombreTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NombreTxt.setForeground(new java.awt.Color(255, 255, 255));
        NombreTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NombreTxt.setBorder(null);
        NombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTxtActionPerformed(evt);
            }
        });
        getContentPane().add(NombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 200, 25));

        referTxt.setBackground(new java.awt.Color(0, 102, 153));
        referTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        referTxt.setForeground(new java.awt.Color(255, 255, 255));
        referTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        referTxt.setBorder(null);
        getContentPane().add(referTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 200, 25));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Referencia:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre producto:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sistema creado por Andre S. © ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        cantidadTxt.setBackground(new java.awt.Color(0, 102, 153));
        cantidadTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cantidadTxt.setForeground(new java.awt.Color(255, 255, 255));
        cantidadTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidadTxt.setBorder(null);
        getContentPane().add(cantidadTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 160, 25));

        agregarBtn.setBackground(new java.awt.Color(0, 102, 153));
        agregarBtn.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        agregarBtn.setForeground(new java.awt.Color(255, 255, 255));
        agregarBtn.setText("Agregar pieza");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(agregarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 200, 30));
        getContentPane().add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtActionPerformed

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        String nombre = NombreTxt.getText().trim();
        String refer = referTxt.getText().trim();
        String cantidad = cantidadTxt.getText().trim();
        long mili = System.currentTimeMillis();
        Date fecha = new Date(mili);

        if (nombre.equals("") || cantidad.equals("") || cantidad.equals("")) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        }else{
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst1 = cn.prepareStatement("select id,cantidad,nombre from inventario where referencia = '"+refer+"'");
                ResultSet rs = pst1.executeQuery();
                if (rs.next()) {
                    id_inve = rs.getInt(1);
                    cantidad_inventario=rs.getInt(2); 
                    
                    if(cantidad_inventario<Integer.parseInt(cantidad)){
                        JOptionPane.showMessageDialog(null, "La cantidad en el invetario es menor, por favor revisar.");
                    }else{
                        try {                        
                        Connection cn2 = Conexion.conectar();
                        PreparedStatement pst = cn2.prepareStatement("insert into inventario_usado values(?,?,?,?,?,?)");
                       
                        pst.setString(1, "0");
                        pst.setInt(2, id_inve);
                        pst.setString(3, num_serie);
                        pst.setInt(4,Integer.parseInt(cantidad) );
                        pst.setString(5, rs.getString(3));
                        pst.setDate(6, fecha);                       
                        pst.executeUpdate();
                        cn2.close();

                        JOptionPane.showMessageDialog(null, "Registro exitoso");

                        this.dispose();
                        
                            try {
                                Connection cn3 = Conexion.conectar();
                                resultado = cantidad_inventario-Integer.parseInt(cantidad);
                                PreparedStatement pst3 = cn3.prepareStatement("update inventario set cantidad=? where id ='"+id_inve+"'");
                                pst3.setInt(1, resultado);
                                pst3.executeLargeUpdate();
                                cn3.close();
                            } catch (SQLException e) {
                                System.err.println("Error al actualizar la cantidad de inventario: "+e);
                            }
                    } catch (SQLException e) {
                        System.err.println("Existe un problema de conexion con la base de datos: " + e);
                    }
                    }
                    cn.close();
                } else {
                    JOptionPane.showMessageDialog(null, "Referencia no registrada, por favor intente con otra referencia");
                    
                }
            } catch (SQLException e) {
                System.err.println("Problema de conexion con la base de datos "+ e);
            }

        }
    }//GEN-LAST:event_agregarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPieza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JButton agregarBtn;
    private javax.swing.JTextField cantidadTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JTextField referTxt;
    // End of variables declaration//GEN-END:variables
}
