/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import java.sql.Date;
import java.sql.*;
import clases.Conexion;


public class RegistroEquipos extends javax.swing.JFrame {

    int id;
    String user;
    String nombre_cli;
    
    
    public RegistroEquipos() {
        
        initComponents();
        id=GestionarClientes.id;
        user= Login.user;
        nombre_cli=infoCliente.nombre_cliente;
        
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon fond = new ImageIcon("src/imagenes/wallpaperPrincipal.jpg");
        Icon fondo = new ImageIcon(fond.getImage().getScaledInstance(jLabelBack.getWidth(), jLabelBack.getHeight(), Image.SCALE_DEFAULT));
        jLabelBack.setIcon(fondo);
        repaint();
        
        
        
        clienteTxt.setText(nombre_cli);
        setTitle("Registro de equipo( "+nombre_cli+" )");
        
    }
    
    @Override
    public Image getIconImage(){
        Image ret = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
        return ret;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        modeloTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        serieTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tipoEqui = new javax.swing.JComboBox<>();
        marcaTxt = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observacionesTxt = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        registroEquipo = new javax.swing.JButton();
        statusTxt = new javax.swing.JTextField();
        clienteTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabelBack = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modeloTxt.setBackground(new java.awt.Color(0, 102, 153));
        modeloTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        modeloTxt.setForeground(new java.awt.Color(255, 255, 255));
        modeloTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        modeloTxt.setBorder(null);
        getContentPane().add(modeloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 200, 25));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Marca:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        serieTxt.setBackground(new java.awt.Color(0, 102, 153));
        serieTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        serieTxt.setForeground(new java.awt.Color(255, 255, 255));
        serieTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        serieTxt.setBorder(null);
        serieTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serieTxtActionPerformed(evt);
            }
        });
        getContentPane().add(serieTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 200, 25));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Observaciones:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Modelo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cliente:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro Equipo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        tipoEqui.setBackground(new java.awt.Color(0, 102, 153));
        tipoEqui.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tipoEqui.setForeground(new java.awt.Color(255, 255, 255));
        tipoEqui.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Laptop", "Impresora", "Telefono", "Desktop", "Tablet" }));
        tipoEqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoEquiActionPerformed(evt);
            }
        });
        getContentPane().add(tipoEqui, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 200, -1));

        marcaTxt.setBackground(new java.awt.Color(0, 102, 153));
        marcaTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        marcaTxt.setForeground(new java.awt.Color(255, 255, 255));
        marcaTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Asus", "Apple", "Samsung", "Lenovo", "Acer", "Hp", "Xiaomi", "Huawei", "Motorola", "Oppo", "Sony", "Cannon", "Epson" }));
        getContentPane().add(marcaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 200, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Numero de serie:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        observacionesTxt.setColumns(20);
        observacionesTxt.setRows(5);
        jScrollPane1.setViewportView(observacionesTxt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 330, 150));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo equipo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        registroEquipo.setBackground(new java.awt.Color(0, 102, 153));
        registroEquipo.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        registroEquipo.setForeground(new java.awt.Color(255, 255, 255));
        registroEquipo.setText("Registrar equipo");
        registroEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(registroEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 200, 30));

        statusTxt.setBackground(new java.awt.Color(0, 102, 153));
        statusTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        statusTxt.setForeground(new java.awt.Color(255, 255, 255));
        statusTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        statusTxt.setText("Ingresado");
        statusTxt.setBorder(null);
        statusTxt.setEnabled(false);
        statusTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTxtActionPerformed(evt);
            }
        });
        getContentPane().add(statusTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 200, 25));

        clienteTxt.setBackground(new java.awt.Color(0, 102, 153));
        clienteTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        clienteTxt.setForeground(new java.awt.Color(255, 255, 255));
        clienteTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        clienteTxt.setBorder(null);
        clienteTxt.setEnabled(false);
        clienteTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteTxtActionPerformed(evt);
            }
        });
        getContentPane().add(clienteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 200, 25));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Estado:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));
        getContentPane().add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serieTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serieTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serieTxtActionPerformed

    private void tipoEquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoEquiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoEquiActionPerformed

    private void registroEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroEquipoActionPerformed
        String marca = marcaTxt.getSelectedItem().toString().trim();
        String tipo = tipoEqui.getSelectedItem().toString().trim();
        String modelo = modeloTxt.getText().trim();
        String serie = serieTxt.getText().trim();
        String obser = observacionesTxt.getText().trim();
        String status = statusTxt.getText().trim();
        long mili = System.currentTimeMillis();
        Date fecha = new Date(mili);

        if (modelo.equals("") || serie.equals("") || obser.equals("")) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        }else if (marca.equals("Seleccionar")||tipo.equals("Seleccionar")) {
            JOptionPane.showMessageDialog(null, "Seleccione una opción");
        }else{
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement("insert into equipos values(?,?,?,?,?,?,?,?,?,?,?)");
                
                
                pst.setInt(1, id);
                pst.setString(2, tipo);
                pst.setString(3, marca);
                pst.setString(4, modelo);
                pst.setString(5, serie);
                pst.setDate(6, fecha);
                pst.setString(7, obser);
                pst.setString(8, status);
                pst.setString(9, user);
                pst.setString(10, "'En proceso'");
                pst.setString(11, "'En proceso'");
                
                pst.executeUpdate();
                cn.close();
                
                
                
                JOptionPane.showMessageDialog(null, "Equipo registrado");

            } catch (SQLException e) {
                System.err.println("Existe un error de conexion con la base de datos " + e);
            }
        }
    }//GEN-LAST:event_registroEquipoActionPerformed

    private void statusTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTxtActionPerformed

    private void clienteTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroEquipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clienteTxt;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> marcaTxt;
    private javax.swing.JTextField modeloTxt;
    private javax.swing.JTextArea observacionesTxt;
    private javax.swing.JButton registroEquipo;
    private javax.swing.JTextField serieTxt;
    private javax.swing.JTextField statusTxt;
    private javax.swing.JComboBox<String> tipoEqui;
    // End of variables declaration//GEN-END:variables
}
