/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;



/**
 *
 * @author leosa
 */
public class Tecnico extends javax.swing.JFrame {

    
    public Tecnico() {
        initComponents();
        this.setTitle("Técnico");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setTitle("Técnico - Sesión de "+Login.user);
        
        ImageIcon fond = new ImageIcon("src/imagenes/wallpaperPrincipal.jpg");
        Icon fondo = new ImageIcon(fond.getImage().getScaledInstance(jLabelBack.getWidth(), jLabelBack.getHeight(), Image.SCALE_DEFAULT));
        jLabelBack.setIcon(fondo);
        repaint();
        
        titulo.setText("Bienvenido "+Login.user);
        
        
    }
    
    @Override
    public Image getIconImage(){
        Image ret = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
        return ret;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        statusBtn = new javax.swing.JButton();
        marcasBtn = new javax.swing.JButton();
        regi = new javax.swing.JLabel();
        regi1 = new javax.swing.JLabel();
        regi2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Registro de Usuarios");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        registerButton.setBackground(new java.awt.Color(204, 204, 204));
        registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/apoyo-tecnico.png"))); // NOI18N
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 100, 90));

        statusBtn.setBackground(new java.awt.Color(204, 204, 204));
        statusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/grafica.png"))); // NOI18N
        statusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusBtnActionPerformed(evt);
            }
        });
        getContentPane().add(statusBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 100, 90));

        marcasBtn.setBackground(new java.awt.Color(204, 204, 204));
        marcasBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inventario.png"))); // NOI18N
        marcasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcasBtnActionPerformed(evt);
            }
        });
        getContentPane().add(marcasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 100, 90));

        regi.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        regi.setForeground(new java.awt.Color(255, 255, 255));
        regi.setText("Inventario");
        getContentPane().add(regi, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        regi1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        regi1.setForeground(new java.awt.Color(255, 255, 255));
        regi1.setText("Gráfica de estatus");
        getContentPane().add(regi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        regi2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        regi2.setForeground(new java.awt.Color(255, 255, 255));
        regi2.setText("Gestión de equipos");
        getContentPane().add(regi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sistema creado por Andre S. © ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));
        getContentPane().add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        new GestionarEquipos().setVisible(true);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void statusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusBtnActionPerformed
        new GraficaStatus().setVisible(true);
    }//GEN-LAST:event_statusBtnActionPerformed

    private void marcasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcasBtnActionPerformed
        new GestionarInventario().setVisible(true);
    }//GEN-LAST:event_marcasBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JButton marcasBtn;
    private javax.swing.JLabel regi;
    private javax.swing.JLabel regi1;
    private javax.swing.JLabel regi2;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton statusBtn;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
